### ISSUE TITLE
是不是15行写错了？？grep写成了ggrep???

### ISSUE THREAD

**Issue by yanwen** [alswl/.oOo.#3]
bash brew-upgrade.sh 
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found
brew-upgrade.sh: line 15: ggrep: command not found

**Comment by alswl** [comment]
使用到了 `grep -P` 参数，所以需要 GNU grep，先安装它： `brew install grep`。

我优化一下脚本，让其先检查该 binary。
